apiVersion: v1
kind: Namespace
metadata:
  name: ats-dev
  labels:
    name: ats-dev
    environment: development

---
apiVersion: v1
kind: Namespace
metadata:
  name: ats-intg
  labels:
    name: ats-intg
    environment: integration