apiVersion: v1
kind: Pod
metadata:
  name: db-client
  namespace: ats-dev
spec:
  containers:
  - name: db-client
    image: postgres:14
    command: ["sleep", "3600"]
    env:
    - name: PGHOST
      value: postgres
    - name: PGUSER
      value: postgres
    - name: PGPASSWORD
      value: postgres
    - name: PGDATABASE
      value: ats_dev
