#!/bin/bash
# Automated cleanup script for obvious dead code
# Generated by identify_obvious_cleanup_candidates.py

set -e

echo '🧹 Starting automated cleanup of obvious dead code...'

# Found 1 functions to remove from 1 files

echo '📝 Processing src/domains/ml/modeling/features/event_features.py...'
# Remove 1 unused functions:
#   - flatten_event_features_for_model (0.00 MB)

echo '✅ Cleanup completed!'
echo 'Next steps:'
echo '1. Review changes: git diff'
echo '2. Run tests: python scripts/run_dev.py test'
echo '3. Commit changes: git add . && git commit -m "cleanup: remove obvious dead code"'