version: '3.9'
services:
  db:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: market-forecast-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TSDB_URL: postgresql://postgres:postgres@db:5432/trading_db
    ports:
      - "8080:8080"
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
    volumes:
      - .:/app

volumes:
  pgdata:
