#!/usr/bin/env python3
"""
Simple Production Worker 1
Launched: 05:14:20
Symbols: 250 (AOS to AXON)
"""
import sys
import os
sys.path.append('/workspace/src')
os.chdir('/workspace')

from scripts.populate_firstrate_minute_bars import main

if __name__ == "__main__":
    sys.argv = [
        'populate_firstrate_minute_bars.py',
        '--asset-type', 'stock',
        '--symbols', 'AOS,AOSL,AOUT,AP,APA,APAM,APCXW,APD,APDN,APEI,APG,APGE,APH,API,APLD,APLE,APLM,APLMW,APLS,APLT,APM,APO,APOG,APOS,APP,APPF,APPN,APPS,APPX,APRE,APT,APTV,APUS,APVO,APWC,APYX,AQB,AQMS,AQN,AQNB,AQST,AQUNR,AQUNU,AR,ARAI,ARAY,ARBB,ARBE,ARBEW,ARBK,ARBKL,ARCB,ARCC,ARCO,ARCT,ARCX,ARDC,ARDS,ARDT,ARDX,ARE,AREB,AREBW,AREC,AREN,ARES,ARGD,ARGX,ARHS,ARI,ARIS,ARKO,ARKOW,ARKR,ARL,ARLO,ARLP,ARM,ARMH,ARMK,ARMN,ARMP,AROC,AROW,ARQ,ARQQ,ARQQW,ARQT,ARR,ARRY,ARTL,ARTNA,ARTV,ARTW,ARVN,ARW,ARWR,ARX,AS,ASA,ASAN,ASB,ASBA,ASBP,ASBPW,ASC,ASG,ASGI,ASGN,ASH,ASIC,ASIX,ASLE,ASM,ASMB,ASML,ASND,ASNS,ASO,ASPC,ASPCR,ASPCU,ASPI,ASPN,ASPS,ASPSW,ASPSZ,ASPU,ASR,ASRT,ASRV,ASST,ASTC,ASTE,ASTH,ASTI,ASTL,ASTLW,ASTS,ASTX,ASUR,ASX,ASYS,ATAI,ATAT,ATCH,ATCOL,ATEC,ATEK,ATEN,ATER,ATEX,ATGE,ATGL,ATHA,ATHE,ATHM,ATHR,ATHS,ATI,ATII,ATIIU,ATIIW,ATKR,ATLC,ATLCL,ATLCP,ATLCZ,ATLN,ATLO,ATLX,ATMC,ATMCR,ATMCU,ATMCW,ATMU,ATMV,ATMVR,ATMVU,ATNFW,ATNI,ATNM,ATO,ATOM,ATOS,ATPC,ATR,ATRA,ATRC,ATRO,ATS,ATUS,ATXG,ATXS,ATYR,AU,AUB,AUBN,AUDC,AUGO,AUID,AUNA,AUPH,AUR,AURA,AUROW,AUST,AUTL,AUUD,AUUDW,AVA,AVAH,AVAL,AVAV,AVB,AVBP,AVD,AVDL,AVDX,AVIR,AVK,AVL,AVNS,AVNT,AVNW,AVO,AVPT,AVPTW,AVR,AVT,AVTR,AVTX,AVXL,AVY,AWF,AWI,AWIN,AWK,AWP,AWR,AWRE,AWX,AX,AXDX,AXGN,AXIL,AXIN,AXINU,AXL,AXON',
        '--checkpoint-file', 'simple_production_worker_1_checkpoint.json',
        '--debug'
    ]
    main()
