#!/usr/bin/env python3
"""
Simple Production Worker 0
Launched: 05:14:16
Symbols: 250 (AEIS to AORT)
"""
import sys
import os
sys.path.append('/workspace/src')
os.chdir('/workspace')

from scripts.populate_firstrate_minute_bars import main

if __name__ == "__main__":
    sys.argv = [
        'populate_firstrate_minute_bars.py',
        '--asset-type', 'stock',
        '--symbols', 'AEIS,AEM,AEMD,AENT,AENTW,AEO,AEON,AEP,AER,AERT,AERTW,AES,AESI,AEVA,AEVAW,AEYE,AFB,AFBI,AFCG,AFG,AFGB,AFGC,AFGD,AFGE,AFIB,AFJK,AFJKR,AFL,AFMD,AFRI,AFRIW,AFRM,AFYA,AG,AGAE,AGCO,AGD,AGEN,AGFY,AGH,AGI,AGIO,AGL,AGM,AGMH,AGNC,AGNCL,AGNCM,AGNCN,AGNCO,AGNCP,AGO,AGRI,AGRO,AGX,AGYS,AHCO,AHG,AHH,AHL,AHR,AHT,AI,AIFE,AIFER,AIFEU,AIFF,AIFU,AIG,AIHS,AII,AIMAU,AIMAW,AIMBU,AIMD,AIMDW,AIN,AIO,AIOT,AIP,AIR,AIRE,AIRG,AIRI,AIRJ,AIRJW,AIRO,AIRS,AIRT,AIRTP,AIS,AISP,AISPW,AIT,AIV,AIXI,AIZ,AIZN,AJG,AKA,AKAM,AKAN,AKBA,AKR,AKRO,AKTX,AL,ALAB,ALAR,ALB,ALBT,ALC,ALCO,ALCY,ALCYU,ALCYW,ALDF,ALDFU,ALDFW,ALDX,ALE,ALEC,ALEX,ALF,ALFUU,ALFUW,ALG,ALGM,ALGN,ALGS,ALGT,ALHC,ALIT,ALK,ALKS,ALKT,ALL,ALLE,ALLO,ALLR,ALLT,ALLY,ALM,ALMS,ALMU,ALNT,ALNY,ALOT,ALRM,ALRS,ALSN,ALTG,ALTI,ALTO,ALTS,ALUR,ALV,ALVO,ALVOW,ALX,ALXO,ALZN,AM,AMAL,AMAT,AMBA,AMBC,AMBI,AMBO,AMBP,AMBQ,AMBR,AMC,AMCR,AMCX,AMD,AME,AMG,AMGN,AMH,AMIX,AMKR,AMLX,AMN,AMOD,AMODW,AMP,AMPE,AMPG,AMPGW,AMPH,AMPL,AMPX,AMPY,AMR,AMRC,AMRK,AMRN,AMRX,AMRZ,AMS,AMSC,AMSF,AMST,AMT,AMTB,AMTD,AMTM,AMTX,AMWD,AMWL,AMX,AMZE,AN,ANAB,ANDE,ANEB,ANET,ANF,ANGH,ANGHW,ANGI,ANGO,ANIK,ANIP,ANIX,ANL,ANNA,ANNAW,ANNX,ANPA,ANRO,ANSC,ANSCU,ANSCW,ANTA,ANTE,ANTX,ANVS,ANY,AOD,AOGO,AOGOW,AOMD,AOMN,AOMR,AON,AONC,AONCW,AORT',
        '--checkpoint-file', 'simple_production_worker_0_checkpoint.json',
        '--debug'
    ]
    main()
