#!/usr/bin/env python3
"""
Simple Production Worker 2
Launched: 05:14:24
Symbols: 250 (AXP to BNED)
"""
import sys
import os
sys.path.append('/workspace/src')
os.chdir('/workspace')

from scripts.populate_firstrate_minute_bars import main

if __name__ == "__main__":
    sys.argv = [
        'populate_firstrate_minute_bars.py',
        '--asset-type', 'stock',
        '--symbols', 'AXP,AXR,AXS,AXSM,AXTA,AXTI,AYI,AYRO,AYTU,AZ,AZI,AZN,AZO,AZTA,AZTR,AZZ,B,BA,BABA,BACK,BAER,BAFN,BAH,BAK,BALL,BALY,BAM,BAMR,BANC,BAND,BANF,BANFP,BANL,BANR,BANX,BAOS,BAP,BARK,BASE,BATL,BATRA,BATRK,BAX,BB,BBAI,BBAR,BBBY,BBCP,BBD,BBDC,BBDO,BBGI,BBIG,BBIO,BBLG,BBLGW,BBLN,BBN,BBSI,BBU,BBUC,BBVA,BBW,BBWI,BBY,BC,BCAB,BCAN,BCAT,BCBP,BCC,BCDA,BCDAW,BCE,BCEL,BCH,BCLI,BCML,BCO,BCOR,BCOV,BCOW,BCPC,BCRX,BCS,BCSF,BCTX,BCTXW,BCV,BCX,BCYC,BDC,BDJ,BDL,BDN,BDRX,BDSX,BDTX,BDX,BE,BEAM,BEAT,BECN,BEDU,BEEM,BEEMW,BEKE,BELFA,BELFB,BEN,BEP,BEPC,BERY,BEST,BFAM,BFC,BFH,BFI,BFIIW,BFIN,BFK,BFLY,BFRG,BFRI,BFRIW,BFS,BFST,BFZ,BG,BGB,BGCP,BGFV,BGH,BGI,BGNE,BGR,BGRY,BGRYW,BGS,BGSF,BGT,BGX,BGXX,BGY,BH,BHAT,BHB,BHC,BHE,BHF,BHFAL,BHFAP,BHG,BHIL,BHK,BHLB,BHM,BHP,BHR,BHSE,BHSEW,BHV,BHVN,BIAF,BIDU,BIG,BIGC,BIGZ,BIIB,BILI,BILL,BIMI,BIO,BIOC,BIOL,BIOR,BIOX,BIP,BIPC,BIRD,BIT,BITF,BIVI,BJ,BJDX,BJRI,BK,BKCC,BKD,BKE,BKH,BKI,BKKT,BKN,BKNG,BKR,BKSC,BKSY,BKT,BKTI,BKU,BKYI,BL,BLAC,BLBD,BLBX,BLCM,BLCO,BLD,BLDE,BLDEW,BLDP,BLDR,BLE,BLEU,BLEUR,BLEUU,BLEUW,BLFS,BLFY,BLIN,BLK,BLKB,BLMN,BLND,BLNK,BLNKW,BLPH,BLRX,BLTE,BLUE,BLW,BLX,BLZE,BMA,BMBL,BME,BMEA,BMEZ,BMI,BMN,BMO,BMR,BMRA,BMRC,BMRN,BMTX,BMY,BN,BNED',
        '--checkpoint-file', 'simple_production_worker_2_checkpoint.json',
        '--debug'
    ]
    main()
