#!/usr/bin/env python3
"""
Simple Production Worker 3
Launched: 05:14:28
Symbols: 250 (BNGO to CCO)
"""
import sys
import os
sys.path.append('/workspace/src')
os.chdir('/workspace')

from scripts.populate_firstrate_minute_bars import main

if __name__ == "__main__":
    sys.argv = [
        'populate_firstrate_minute_bars.py',
        '--asset-type', 'stock',
        '--symbols', 'BNGO,BNGOW,BNL,BNMV,BNOX,BNR,BNRE,BNRG,BNS,BNSO,BNTC,BNTX,BNY,BOC,BODY,BOE,BOF,BOH,BOKF,BOLT,BON,BOOM,BOOT,BORR,BOSC,BOTJ,BOWL,BOX,BOXD,BOXL,BP,BPMC,BPOP,BPRN,BPT,BPTH,BPTS,BPYPP,BQ,BR,BRAG,BRBR,BRBS,BRC,BRCC,BRDG,BRDS,BREA,BRFH,BRFS,BRID,BRIV,BRIVU,BRIVW,BRKL,BRKR,BRLT,BRN,BRO,BROG,BROGW,BROS,BRP,BRQS,BRSH,BRSP,BRT,BRTX,BRW,BRX,BRY,BRZE,BSAC,BSBK,BSBR,BSET,BSFC,BSGM,BSIG,BSKYU,BSKYW,BSL,BSM,BSMX,BSQR,BSRR,BST,BSTZ,BSVN,BSX,BSY,BTA,BTAI,BTB,BTBD,BTBDW,BTBT,BTCM,BTCS,BTCY,BTG,BTI,BTMD,BTMDW,BTN,BTO,BTOG,BTT,BTTR,BTTX,BTU,BTWN,BTWNU,BTWNW,BTX,BTZ,BUD,BUI,BUR,BURL,BURU,BUSE,BV,BVH,BVN,BVS,BVXV,BW,BWA,BWAQ,BWAY,BWB,BWEN,BWFG,BWG,BWMN,BWMX,BWV,BWXT,BX,BXC,BXMT,BXMX,BXP,BXRX,BXSL,BY,BYD,BYFC,BYM,BYN,BYND,BYNO,BYRN,BYSI,BZ,BZFD,BZFDW,BZH,BZUN,CAAP,CAAS,CABA,CABO,CAC,CACC,CACI,CACO,CADE,CADL,CAE,CAF,CAG,CAH,CAKE,CAL,CALA,CALB,CALM,CALT,CALX,CAMP,CAMT,CAN,CANB,CANF,CANG,CANO,CAPD,CAPL,CAPR,CAR,CARA,CARE,CARG,CARM,CARR,CARS,CARV,CASA,CASH,CASI,CASS,CASY,CAT,CATC,CATO,CATX,CATY,CAVA,CB,CBAN,CBAT,CBAY,CBD,CBFV,CBH,CBIO,CBL,CBNK,CBOE,CBRE,CBRG,CBRGU,CBRGW,CBRL,CBSH,CBT,CBTX,CBU,CBZ,CC,CCAP,CCB,CCBG,CCCC,CCCS,CCEL,CCEP,CCF,CCI,CCJ,CCK,CCL,CCLD,CCLP,CCM,CCNC,CCNE,CCO',
        '--checkpoint-file', 'simple_production_worker_3_checkpoint.json',
        '--debug'
    ]
    main()
