apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-prod
  namespace: ats-prod
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_USER: cG9zdGdyZXM=
  TSDB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQGRiLXNlcnZpY2U6NTQzMi90cmFkaW5nX2RiX3Byb2Q=