apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-env
  namespace: ats-env
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_USER: cG9zdGdyZXM=
  TSDB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQGxvY2FsaG9zdDo1NDMyL3RyYWRpbmdfZGJfdGVzdA==