apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: ats-dev
type: Opaque
data:
  # Git credentials (base64 encoded)
  git-token: Z2hwXzI2RmRqMU1UMmlRVnNCQ2J1N0RmY2NWb1V3YktEbTRQU01ocg==  # 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
  git-repo-url: aHR0cHM6Ly9naXRodWIuY29tL0Frb2xvVGVjaG5vbG9naWVzL2F0cy1nZW5haS5naXQ=  # https://github.com/AkoloTechnologies/ats-genai.git