apiVersion: apps/v1
kind: Deployment
metadata:
  name: ats-api
spec:
  replicas: 3  # Three replicas for prod HA
  template:
    spec:
      containers:
      - name: ats-api
        env:
        - name: ENVIRONMENT
          value: "prod"
        - name: LOG_LEVEL
          value: "WARNING"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
