"""
Multi-Time Horizon PyTorch DataLoader for Financial Sequence Modeling

This module implements a PyTorch DataLoader that loads features from existing
ArrayRecord files generated by FeatureExtractionRunner, aligns multiple timeframes,
and generates training sequences for multi-horizon forecasting models.

Based on 2024-2025 research on:
- Temporal Fusion Transformers (TFT) with multi-horizon attention
- Hierarchical Spatio-Temporal Attention (18.4% RMSE reduction)
- Multi-Scale Self-Supervised Learning with temporal alignment
- Sparse Transformer with multi-scale attention patterns

Architecture:
    MultiTimeHorizonDataset (PyTorch Dataset)
    ├── TemporalFeatureAligner (handles time synchronization)
    ├── MultiScaleSequenceBuilder (creates hierarchical sequences)
    └── FeatureService (existing ArrayRecord reader)
"""

import logging
from typing import Dict, List, Tuple, Optional, Union
from dataclasses import dataclass
from datetime import datetime, timedelta
import asyncio
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

from domains.services.training_data.arrayrecord_feature_reader import (
    FeatureService, FeatureRequest, FeatureDataResult
)

logger = logging.getLogger(__name__)


@dataclass
class MultiTimeHorizonConfig:
    """Configuration for multi-time horizon sequence modeling."""
    
    # Time horizon configuration
    timeframes: List[str] = None  # ['5m', '15m', '1h', '1d']
    base_timeframe: str = '5m'    # Primary timeframe for sequence generation
    
    # Sequence configuration  
    sequence_length: int = 144    # 12 hours of 5-minute data
    prediction_horizons: List[int] = None  # [1, 3, 6, 12, 24] steps ahead
    
    # Feature configuration
    feature_groups: List[str] = None  # ['ohlcv_basic', 'technical_momentum']
    target_features: List[str] = None  # ['close', 'returns']
    
    # Alignment configuration
    alignment_method: str = 'forward_fill'  # 'forward_fill', 'interpolate'
    max_missing_ratio: float = 0.15
    
    # Data filtering
    min_volume_threshold: float = 1000.0
    exclude_market_hours: bool = False
    
    def __post_init__(self):
        if self.timeframes is None:
            self.timeframes = ['5m', '15m', '1h', '1d']
        if self.prediction_horizons is None:
            self.prediction_horizons = [1, 3, 6, 12, 24]
        if self.feature_groups is None:
            self.feature_groups = ['ohlcv_basic', 'technical_momentum']
        if self.target_features is None:
            self.target_features = ['close', 'returns']


class TemporalFeatureAligner:
    """
    Aligns features from different timeframes to the same timestamps.
    
    Implements temporal alignment strategies for multi-scale modeling:
    - Forward fill for OHLCV data
    - Time-weighted interpolation for technical indicators
    - Attention masking for missing data points
    """
    
    def __init__(self, config: MultiTimeHorizonConfig):
        self.config = config
        self.logger = logging.getLogger(__name__)
        
    def align_multi_timeframe_features(
        self, 
        feature_data: Dict[str, FeatureDataResult],
        target_timestamps: pd.DatetimeIndex
    ) -> Dict[str, torch.Tensor]:
        """
        Align features from multiple timeframes to target timestamps.
        
        Args:
            feature_data: Dict mapping timeframe to FeatureDataResult
            target_timestamps: Target datetime index for alignment
            
        Returns:
            Dict mapping feature_name to aligned tensor [T, F] where:
            - T: number of time steps (len(target_timestamps))
            - F: feature dimensions
        """
        aligned_features = {}
        
        for timeframe, result in feature_data.items():
            timeframe_features = self._align_timeframe_features(
                result, target_timestamps, timeframe
            )
            
            # Add timeframe prefix to feature names
            for feature_name, tensor in timeframe_features.items():
                aligned_name = f"{timeframe}_{feature_name}"
                aligned_features[aligned_name] = tensor
                
        return aligned_features
    
    def _align_timeframe_features(
        self,
        result: FeatureDataResult,
        target_timestamps: pd.DatetimeIndex,
        timeframe: str
    ) -> Dict[str, torch.Tensor]:
        """Align features from a single timeframe to target timestamps."""
        
        # Convert sequence data to DataFrame
        if not result.sequence_data:
            self.logger.warning(f"No sequence data for {timeframe}")
            return self._create_empty_features(target_timestamps, result.ohlc)
            
        df = pd.DataFrame(result.sequence_data)
        
        # Ensure datetime column exists and is datetime type
        if 'datetime' not in df.columns:
            self.logger.error(f"No datetime column in {timeframe} data")
            return self._create_empty_features(target_timestamps, result.ohlc)
            
        df['datetime'] = pd.to_datetime(df['datetime'])
        df.set_index('datetime', inplace=True)
        df.sort_index(inplace=True)
        
        # Reindex to target timestamps with forward fill
        aligned_df = df.reindex(target_timestamps, method='ffill')
        
        # Handle missing data based on configuration
        if self.config.alignment_method == 'forward_fill':
            aligned_df = aligned_df.ffill()
        elif self.config.alignment_method == 'interpolate':
            aligned_df = aligned_df.interpolate(method='time')
            
        # Fill remaining NaNs with zeros
        aligned_df = aligned_df.fillna(0.0)
        
        # Convert to tensors
        feature_tensors = {}
        for column in aligned_df.columns:
            if aligned_df[column].dtype in [np.float64, np.float32, np.int64, np.int32]:
                tensor = torch.tensor(
                    aligned_df[column].values.astype(np.float32),
                    dtype=torch.float32
                ).unsqueeze(-1)  # Add feature dimension
                feature_tensors[column] = tensor
                
        return feature_tensors
    
    def _create_empty_features(
        self, 
        target_timestamps: pd.DatetimeIndex,
        ohlc: Dict[str, float]
    ) -> Dict[str, torch.Tensor]:
        """Create empty feature tensors when no data is available."""
        empty_features = {}
        
        # Create basic OHLCV features from latest values
        for feature in ['open', 'high', 'low', 'close', 'volume']:
            if feature in ohlc:
                # Repeat last known value
                value = ohlc[feature]
                tensor = torch.full(
                    (len(target_timestamps), 1),
                    value,
                    dtype=torch.float32
                )
                empty_features[feature] = tensor
                
        return empty_features


class MultiScaleSequenceBuilder:
    """
    Builds training sequences with multiple time horizons.
    
    Implements hierarchical sequence structures for attention mechanisms:
    - Local sequences (5m, 15m) for short-term patterns
    - Global sequences (1h, 1d) for long-term trends
    - Cross-scale attention masks for temporal dependencies
    """
    
    def __init__(self, config: MultiTimeHorizonConfig):
        self.config = config
        self.logger = logging.getLogger(__name__)
        
    def build_sequence_batch(
        self,
        aligned_features: Dict[str, torch.Tensor],
        target_features: Dict[str, torch.Tensor],
        timestamps: pd.DatetimeIndex
    ) -> Tuple[Dict[str, torch.Tensor], torch.Tensor, Dict[str, torch.Tensor]]:
        """
        Build hierarchical sequence batches for multi-horizon modeling.
        
        Args:
            aligned_features: Aligned features from all timeframes
            target_features: Target values for prediction
            timestamps: Corresponding timestamps
            
        Returns:
            Tuple of (features_by_scale, targets, attention_masks)
        """
        
        # Group features by timeframe scale
        features_by_scale = self._group_features_by_scale(aligned_features)
        
        # Create sequences for each scale
        sequence_features = {}
        attention_masks = {}
        
        for scale, features in features_by_scale.items():
            scale_sequences, scale_mask = self._create_scale_sequences(
                features, scale
            )
            sequence_features[scale] = scale_sequences
            attention_masks[scale] = scale_mask
            
        # Process targets for multiple horizons
        target_sequences = self._create_target_sequences(target_features)
        
        return sequence_features, target_sequences, attention_masks
    
    def _group_features_by_scale(
        self, 
        aligned_features: Dict[str, torch.Tensor]
    ) -> Dict[str, Dict[str, torch.Tensor]]:
        """Group features by timeframe scale."""
        
        features_by_scale = {}
        
        for feature_name, tensor in aligned_features.items():
            # Extract timeframe from feature name (e.g., "5m_close" -> "5m")
            parts = feature_name.split('_', 1)
            if len(parts) == 2 and parts[0] in self.config.timeframes:
                timeframe = parts[0]
                base_feature = parts[1]
                
                if timeframe not in features_by_scale:
                    features_by_scale[timeframe] = {}
                features_by_scale[timeframe][base_feature] = tensor
            else:
                # Default to base timeframe for features without prefix
                if self.config.base_timeframe not in features_by_scale:
                    features_by_scale[self.config.base_timeframe] = {}
                features_by_scale[self.config.base_timeframe][feature_name] = tensor
                
        return features_by_scale
    
    def _create_scale_sequences(
        self,
        scale_features: Dict[str, torch.Tensor],
        scale: str
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Create sequences and attention masks for a specific scale."""
        
        if not scale_features:
            # Return empty tensors
            empty_seq = torch.zeros((self.config.sequence_length, 1))
            empty_mask = torch.zeros(self.config.sequence_length, dtype=torch.bool)
            return empty_seq, empty_mask
            
        # Stack all features for this scale
        feature_list = []
        for feature_name, tensor in scale_features.items():
            feature_list.append(tensor)
            
        # Concatenate features along feature dimension
        stacked_features = torch.cat(feature_list, dim=-1)  # [T, F]
        
        # Check if we need padding
        original_size = stacked_features.size(0)
        needs_padding = original_size < self.config.sequence_length
        
        if needs_padding:
            # Pad with zeros at the beginning
            padding_size = self.config.sequence_length - original_size
            padding = torch.zeros(
                (padding_size, stacked_features.size(-1)),
                dtype=stacked_features.dtype
            )
            stacked_features = torch.cat([padding, stacked_features], dim=0)
            
        # Take the last sequence_length steps
        sequence = stacked_features[-self.config.sequence_length:]
        
        # Create attention mask (True for valid data, False for padding)
        mask = torch.ones(self.config.sequence_length, dtype=torch.bool)
        
        # Mark padded positions as masked
        if needs_padding:
            padding_size = self.config.sequence_length - original_size
            mask[:padding_size] = False
            
        return sequence, mask
    
    def _create_target_sequences(
        self,
        target_features: Dict[str, torch.Tensor]
    ) -> torch.Tensor:
        """Create target sequences for multiple prediction horizons."""
        
        # Use the first target feature as primary target
        target_name = list(target_features.keys())[0]
        target_tensor = target_features[target_name]
        
        # Create targets for each prediction horizon
        targets = []
        for horizon in self.config.prediction_horizons:
            if target_tensor.size(0) > horizon:
                # Future value at this horizon
                target_value = target_tensor[-horizon - 1:-horizon]
            else:
                # Not enough data, use last available value
                target_value = target_tensor[-1:]
                
            targets.append(target_value)
            
        # Stack targets [num_horizons, 1]
        return torch.cat(targets, dim=0)


class MultiTimeHorizonDataset(Dataset):
    """
    PyTorch Dataset for multi-time horizon financial sequence modeling.
    
    Loads pre-computed features from ArrayRecord files and creates aligned
    sequences across multiple timeframes for training TFT and other
    multi-scale attention models.
    """
    
    def __init__(
        self,
        symbols: List[str],
        date_range: Tuple[datetime, datetime],
        config: MultiTimeHorizonConfig,
        feature_service: Optional[FeatureService] = None
    ):
        """
        Initialize multi-time horizon dataset.
        
        Args:
            symbols: List of symbols to include
            date_range: (start_date, end_date) tuple
            config: Configuration for multi-horizon modeling
            feature_service: Existing FeatureService instance (optional)
        """
        self.symbols = symbols
        self.date_range = date_range
        self.config = config
        
        # Initialize components
        self.feature_service = feature_service or FeatureService()
        self.temporal_aligner = TemporalFeatureAligner(config)
        self.sequence_builder = MultiScaleSequenceBuilder(config)
        
        # Cache for loaded data
        self._data_cache = {}
        
        # Generate sample indices
        self.samples = self._generate_samples()
        
        self.logger = logging.getLogger(__name__)
        self.logger.info(f"Initialized dataset with {len(self.samples)} samples")
        
    def _generate_samples(self) -> List[Tuple[str, datetime]]:
        """Generate list of (symbol, datetime) samples for training."""
        samples = []
        
        start_date, end_date = self.date_range
        current_date = start_date
        
        # Generate samples every hour (can be adjusted)
        delta = timedelta(hours=1)
        
        while current_date <= end_date:
            for symbol in self.symbols:
                samples.append((symbol, current_date))
            current_date += delta
            
        return samples
    
    def __len__(self) -> int:
        return len(self.samples)
    
    def __getitem__(self, idx: int) -> Tuple[Dict[str, torch.Tensor], torch.Tensor, Dict[str, torch.Tensor]]:
        """
        Get a training sample.
        
        Returns:
            Tuple of (features_by_scale, targets, attention_masks)
        """
        symbol, target_datetime = self.samples[idx]
        
        try:
            # Load features for all timeframes
            feature_data = self._load_multi_timeframe_features(symbol, target_datetime)
            
            # Generate target timestamps for alignment
            target_timestamps = self._generate_target_timestamps(
                target_datetime, self.config.sequence_length
            )
            
            # Align features across timeframes
            aligned_features = self.temporal_aligner.align_multi_timeframe_features(
                feature_data, target_timestamps
            )
            
            # Extract target features
            target_features = self._extract_target_features(aligned_features)
            
            # Build sequences
            sequence_features, targets, attention_masks = (
                self.sequence_builder.build_sequence_batch(
                    aligned_features, target_features, target_timestamps
                )
            )
            
            return sequence_features, targets, attention_masks
            
        except Exception as e:
            self.logger.error(f"Error loading sample {idx} ({symbol}, {target_datetime}): {e}")
            
            # Return empty data for failed samples
            return self._create_empty_sample()
    
    def _load_multi_timeframe_features(
        self, 
        symbol: str, 
        target_datetime: datetime
    ) -> Dict[str, FeatureDataResult]:
        """Load features for all configured timeframes."""
        
        cache_key = f"{symbol}_{target_datetime.isoformat()}"
        
        if cache_key in self._data_cache:
            return self._data_cache[cache_key]
        
        feature_data = {}
        
        # Load features for each timeframe
        for timeframe in self.config.timeframes:
            try:
                request = FeatureRequest(
                    symbol=symbol,
                    target_datetime=target_datetime,
                    feature_groups=self.config.feature_groups,
                    timeframe=timeframe
                )
                
                # Use asyncio to run async method
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
                
                try:
                    result = loop.run_until_complete(
                        self.feature_service.get_feature_data(request)
                    )
                    feature_data[timeframe] = result
                finally:
                    loop.close()
                    
            except Exception as e:
                self.logger.warning(f"Failed to load {timeframe} data for {symbol}: {e}")
                
        # Cache the result
        self._data_cache[cache_key] = feature_data
        
        return feature_data
    
    def _generate_target_timestamps(
        self, 
        target_datetime: datetime, 
        sequence_length: int
    ) -> pd.DatetimeIndex:
        """Generate timestamp sequence ending at target_datetime."""
        
        # For 5-minute base timeframe
        freq_map = {
            '5m': '5min',
            '15m': '15min', 
            '1h': '1H',
            '1d': '1D'
        }
        
        freq = freq_map.get(self.config.base_timeframe, '5min')
        
        # Generate timestamps going backward from target
        end_time = target_datetime
        start_time = end_time - pd.Timedelta(minutes=5 * sequence_length)
        
        timestamps = pd.date_range(
            start=start_time,
            end=end_time,
            freq=freq
        )
        
        return timestamps[-sequence_length:]  # Take last sequence_length points
    
    def _extract_target_features(
        self,
        aligned_features: Dict[str, torch.Tensor]
    ) -> Dict[str, torch.Tensor]:
        """Extract target features for prediction."""
        
        target_features = {}
        
        for target_name in self.config.target_features:
            # Look for target in base timeframe first
            feature_key = f"{self.config.base_timeframe}_{target_name}"
            
            if feature_key in aligned_features:
                target_features[target_name] = aligned_features[feature_key]
            elif target_name in aligned_features:
                target_features[target_name] = aligned_features[target_name]
            else:
                self.logger.warning(f"Target feature {target_name} not found")
                
        return target_features
    
    def _create_empty_sample(self) -> Tuple[Dict[str, torch.Tensor], torch.Tensor, Dict[str, torch.Tensor]]:
        """Create empty sample for failed data loading."""
        
        # Create empty features for each scale
        empty_features = {}
        empty_masks = {}
        
        for timeframe in self.config.timeframes:
            empty_features[timeframe] = torch.zeros((self.config.sequence_length, 1))
            empty_masks[timeframe] = torch.zeros(self.config.sequence_length, dtype=torch.bool)
            
        # Empty targets
        empty_targets = torch.zeros(len(self.config.prediction_horizons))
        
        return empty_features, empty_targets, empty_masks


def create_multi_horizon_dataloader(
    symbols: List[str],
    date_range: Tuple[datetime, datetime],
    config: MultiTimeHorizonConfig,
    batch_size: int = 32,
    shuffle: bool = True,
    num_workers: int = 0,
    feature_service: Optional[FeatureService] = None
) -> DataLoader:
    """
    Create a PyTorch DataLoader for multi-time horizon training.
    
    Args:
        symbols: List of symbols to include
        date_range: (start_date, end_date) tuple
        config: Configuration for multi-horizon modeling
        batch_size: Batch size for training
        shuffle: Whether to shuffle samples
        num_workers: Number of worker processes
        feature_service: Existing FeatureService instance
        
    Returns:
        PyTorch DataLoader ready for training
    """
    
    dataset = MultiTimeHorizonDataset(
        symbols=symbols,
        date_range=date_range,
        config=config,
        feature_service=feature_service
    )
    
    def collate_fn(batch):
        """Custom collate function for variable-length sequences."""
        
        features_batch = {}
        targets_batch = []
        masks_batch = {}
        
        # Separate features, targets, and masks
        for features, targets, masks in batch:
            targets_batch.append(targets)
            
            for scale, feature_tensor in features.items():
                if scale not in features_batch:
                    features_batch[scale] = []
                features_batch[scale].append(feature_tensor)
                
            for scale, mask_tensor in masks.items():
                if scale not in masks_batch:
                    masks_batch[scale] = []
                masks_batch[scale].append(mask_tensor)
        
        # Stack tensors
        stacked_features = {}
        for scale, tensors in features_batch.items():
            stacked_features[scale] = torch.stack(tensors, dim=0)
            
        stacked_targets = torch.stack(targets_batch, dim=0)
        
        stacked_masks = {}
        for scale, tensors in masks_batch.items():
            stacked_masks[scale] = torch.stack(tensors, dim=0)
            
        return stacked_features, stacked_targets, stacked_masks
    
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        collate_fn=collate_fn,
        pin_memory=True
    )


# Example usage
if __name__ == "__main__":
    
    # Configuration
    config = MultiTimeHorizonConfig(
        timeframes=['5m', '15m', '1h', '1d'],
        base_timeframe='5m',
        sequence_length=144,  # 12 hours of 5-minute data
        prediction_horizons=[1, 3, 6, 12, 24],
        feature_groups=['ohlcv_basic', 'technical_momentum'],
        target_features=['close', 'returns']
    )
    
    # Create data loader
    symbols = ['AAPL', 'TSLA', 'MSFT']
    date_range = (
        datetime(2024, 1, 1),
        datetime(2024, 12, 31)
    )
    
    dataloader = create_multi_horizon_dataloader(
        symbols=symbols,
        date_range=date_range,
        config=config,
        batch_size=32,
        shuffle=True
    )
    
    # Example training loop
    for batch_idx, (features, targets, masks) in enumerate(dataloader):
        print(f"Batch {batch_idx}:")
        print(f"  Features: {[(k, v.shape) for k, v in features.items()]}")
        print(f"  Targets: {targets.shape}")
        print(f"  Masks: {[(k, v.shape) for k, v in masks.items()]}")
        
        if batch_idx >= 2:  # Just show first few batches
            break