apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: ats-prod
type: Opaque
stringData:
  webhook-url: "https://hooks.slack.com/services/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"