apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: ats-prod
type: Opaque
stringData:
  webhook-url: "https://hooks.slack.com/services/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"