apiVersion: batch/v1
kind: Job
metadata:
  name: create-sample-dev-tables
  namespace: ats-dev
spec:
  template:
    spec:
      containers:
      - name: setup
        image: postgres:14
        command: ["/bin/bash"]
        args:
        - "-c"
        - "/scripts/create_sample_dev_tables_job_1.sql"