apiVersion: v1
kind: Pod
metadata:
  name: data-access
  namespace: ats-dev
spec:
  containers:
  - name: data-access
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data-volume
      mountPath: /data
    - name: backtest-volume
      mountPath: /backtest
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc
  - name: backtest-volume
    persistentVolumeClaim:
      claimName: backtest-pvc