apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-dev-to-intg
  namespace: ats-dev
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: python:3.11-slim
        command: ["/bin/bash"]
        args:
        - "-c"
        - "/scripts/migrate_dev_to_intg_job_1.py"