apiVersion: v1
kind: Service
metadata:
  name: market-forecast-app
spec:
  type: LoadBalancer
  selector:
    app: market-forecast-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
