apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instrument-agent-logs
  namespace: ats-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instrument-agent-reports
  namespace: ats-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
