apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ats-intg

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: ats-genai
  newTag: intg-latest

commonLabels:
  environment: intg
