# Base network policies
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ats-platform-network-policy
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ats-dev
  egress:
  - {} # Allow all egress for now