#!/bin/bash
# Auto-generated script to remove duplicate test files
# Generated by scripts/detect_duplicate_test_files.py

# set -e  # Don't exit on error (some files may already be removed)

echo "🗑️  Removing duplicate test files..."
echo "=" * 60


# Remove duplicate of tests/infrastructure/database/test_migration_manager_prefixing.py
echo "Removing tests/infrastructure/db/test_migration_manager_prefixing.py..."
rm -f "tests/infrastructure/db/test_migration_manager_prefixing.py"

# Remove duplicate of tests/infrastructure/database/test_migration_manager_comprehensive.py
echo "Removing tests/infrastructure/db/test_migration_manager_comprehensive.py..."
rm -f "tests/infrastructure/db/test_migration_manager_comprehensive.py"

# Remove duplicate of tests/infrastructure/database/test_db_naming.py
echo "Removing tests/infrastructure/db/test_db_naming.py..."
rm -f "tests/infrastructure/db/test_db_naming.py"

# Remove duplicate of tests/infrastructure/database/test_migration_manager.py
echo "Removing tests/infrastructure/db/test_migration_manager.py..."
rm -f "tests/infrastructure/db/test_migration_manager.py"

# Remove duplicate of tests/infrastructure/database/test_migration_manager_comprehensive_fixed.py
echo "Removing tests/infrastructure/db/test_migration_manager_comprehensive_fixed.py..."
rm -f "tests/infrastructure/db/test_migration_manager_comprehensive_fixed.py"

# Remove duplicate of tests/infrastructure/database/test_dao_base.py
echo "Removing tests/core/dao/test_dao_base.py..."
rm -f "tests/core/dao/test_dao_base.py"

# Remove duplicate of tests/domains/analytics/services/test_eda_unified_metadata_system.py
echo "Removing tests/infrastructure/integration/test_eda_unified_metadata_system.py..."
rm -f "tests/infrastructure/integration/test_eda_unified_metadata_system.py"

# Remove duplicate of tests/domains/instruments/services/test_data_population_issues.py
echo "Removing tests/infrastructure/integration/test_data_population_issues.py..."
rm -f "tests/infrastructure/integration/test_data_population_issues.py"

# Remove duplicate of tests/domains/analytics/services/test_eda_database_fallback_system.py
echo "Removing tests/infrastructure/integration/test_eda_database_fallback_system.py..."
rm -f "tests/infrastructure/integration/test_eda_database_fallback_system.py"

# Remove duplicate of tests/domains/analytics/services/test_eda_javascript_loading.py
echo "Removing tests/infrastructure/integration/test_eda_javascript_loading.py..."
rm -f "tests/infrastructure/integration/test_eda_javascript_loading.py"

# Remove duplicate of tests/domains/analytics/services/test_eda_threading_server_fix.py
echo "Removing tests/infrastructure/integration/test_eda_threading_server_fix.py..."
rm -f "tests/infrastructure/integration/test_eda_threading_server_fix.py"

# Remove duplicate of tests/domains/market_data/test_market_cap_calculation_accuracy.py
echo "Removing tests/infrastructure/market_data/test_market_cap_calculation_accuracy.py..."
rm -f "tests/infrastructure/market_data/test_market_cap_calculation_accuracy.py"

# Remove duplicate of tests/domains/market_data/test_optimized_data_pipeline_performance.py
echo "Removing tests/infrastructure/market_data/test_optimized_data_pipeline_performance.py..."
rm -f "tests/infrastructure/market_data/test_optimized_data_pipeline_performance.py"

# Remove duplicate of tests/domains/market_data/test_unified_db_daily_price_market_data_manager.py
echo "Removing tests/infrastructure/market_data/test_unified_db_daily_price_market_data_manager.py..."
rm -f "tests/infrastructure/market_data/test_unified_db_daily_price_market_data_manager.py"

# Remove duplicate of tests/domains/market_data/test_market_data_streamer.py
echo "Removing tests/infrastructure/market_data/test_market_data_streamer.py..."
rm -f "tests/infrastructure/market_data/test_market_data_streamer.py"

# Remove duplicate of tests/domains/market_data/test_signals.py
echo "Removing tests/infrastructure/market_data/test_signals.py..."
rm -f "tests/infrastructure/market_data/test_signals.py"

# Remove duplicate of tests/domains/market_data/test_unified_mgr.py
echo "Removing tests/infrastructure/market_data/test_unified_mgr.py..."
rm -f "tests/infrastructure/market_data/test_unified_mgr.py"

# Remove duplicate of tests/domains/market_data/test_market_data_simulator.py
echo "Removing tests/infrastructure/market_data/test_market_data_simulator.py..."
rm -f "tests/infrastructure/market_data/test_market_data_simulator.py"

# Remove duplicate of tests/domains/market_data/test_multi_timeframe_ohlc_signals.py
echo "Removing tests/infrastructure/market_data/test_multi_timeframe_ohlc_signals.py..."
rm -f "tests/infrastructure/market_data/test_multi_timeframe_ohlc_signals.py"

# Remove duplicate of tests/domains/analytics/services/test_analytics_schema_validation.py
echo "Removing tests/infrastructure/services/analytics/test_analytics_schema_validation.py..."
rm -f "tests/infrastructure/services/analytics/test_analytics_schema_validation.py"

# Remove duplicate of tests/domains/analytics/services/test_enhanced_analytics.py
echo "Removing tests/infrastructure/services/analytics/test_enhanced_analytics.py..."
rm -f "tests/infrastructure/services/analytics/test_enhanced_analytics.py"

# Remove duplicate of tests/domains/analytics/services/test_analytics_endpoints.py
echo "Removing tests/infrastructure/services/analytics/test_analytics_endpoints.py..."
rm -f "tests/infrastructure/services/analytics/test_analytics_endpoints.py"

# Remove duplicate of tests/domains/analytics/services/test_agent_endpoints.py
echo "Removing tests/infrastructure/services/analytics/test_agent_endpoints.py..."
rm -f "tests/infrastructure/services/analytics/test_agent_endpoints.py"

# Remove duplicate of tests/domains/analytics/services/test_query_performance.py
echo "Removing tests/infrastructure/services/analytics/test_query_performance.py..."
rm -f "tests/infrastructure/services/analytics/test_query_performance.py"

# Remove duplicate of tests/infrastructure/services/data_services/test_dataset_service_feature_metadata_integration.py
echo "Removing tests/services/data_services/test_dataset_service_feature_metadata_integration.py..."
rm -f "tests/services/data_services/test_dataset_service_feature_metadata_integration.py"

# Remove duplicate of tests/infrastructure/services/data_services/test_dataset_api_contract.py
echo "Removing tests/services/data_services/test_dataset_api_contract.py..."
rm -f "tests/services/data_services/test_dataset_api_contract.py"

# Remove duplicate of tests/infrastructure/services/data_services/test_checkpoint_framework.py
echo "Removing tests/services/data_services/test_checkpoint_framework.py..."
rm -f "tests/services/data_services/test_checkpoint_framework.py"

# Remove duplicate of tests/infrastructure/services/data_services/test_dataset_detail_page_regression_protection.py
echo "Removing tests/services/data_services/test_dataset_detail_page_regression_protection.py..."
rm -f "tests/services/data_services/test_dataset_detail_page_regression_protection.py"

# Remove duplicate of tests/infrastructure/services/data_services/test_tsla_direct_check.py
echo "Removing tests/services/data_services/test_tsla_direct_check.py..."
rm -f "tests/services/data_services/test_tsla_direct_check.py"

# Remove duplicate of tests/infrastructure/services/core/app/test_runner_interval_bug_fix.py
echo "Removing tests/services/core/app/test_runner_interval_bug_fix.py..."
rm -f "tests/services/core/app/test_runner_interval_bug_fix.py"

# Remove duplicate of tests/infrastructure/services/core/app/test_runner_interval_generation.py
echo "Removing tests/services/core/app/test_runner_interval_generation.py..."
rm -f "tests/services/core/app/test_runner_interval_generation.py"

# Remove duplicate of tests/infrastructure/interfaces/rest_api/test_backtest_analytics_api.py
echo "Removing tests/interfaces/rest_api/test_backtest_analytics_api.py..."
rm -f "tests/interfaces/rest_api/test_backtest_analytics_api.py"

# Remove duplicate of tests/domains/market_data/utils/test_adjusted_price.py
echo "Removing tests/infrastructure/market_data/utils/test_adjusted_price.py..."
rm -f "tests/infrastructure/market_data/utils/test_adjusted_price.py"

# Remove duplicate of tests/domains/market_data/eod/test_db_daily_price_market_data_manager_dao.py
echo "Removing tests/infrastructure/market_data/eod/test_db_daily_price_market_data_manager_dao.py..."
rm -f "tests/infrastructure/market_data/eod/test_db_daily_price_market_data_manager_dao.py"

# Remove duplicate of tests/domains/market_data/eod/test_unify_daily_prices_regression.py
echo "Removing tests/infrastructure/market_data/eod/test_unify_daily_prices_regression.py..."
rm -f "tests/infrastructure/market_data/eod/test_unify_daily_prices_regression.py"

# Remove duplicate of tests/domains/market_data/eod/test_unified_daily_price_validation.py
echo "Removing tests/infrastructure/market_data/eod/test_unified_daily_price_validation.py..."
rm -f "tests/infrastructure/market_data/eod/test_unified_daily_price_validation.py"

# Remove duplicate of tests/domains/market_data/eod/test_file_daily_price_market_data_manager.py
echo "Removing tests/infrastructure/market_data/eod/test_file_daily_price_market_data_manager.py..."
rm -f "tests/infrastructure/market_data/eod/test_file_daily_price_market_data_manager.py"

# Remove duplicate of tests/domains/market_data/eod/test_turbo_price_backfill_integration.py
echo "Removing tests/infrastructure/market_data/eod/test_turbo_price_backfill_integration.py..."
rm -f "tests/infrastructure/market_data/eod/test_turbo_price_backfill_integration.py"

# Remove duplicate of tests/domains/market_data/eod/test_unify_daily_prices_db.py
echo "Removing tests/infrastructure/market_data/eod/test_unify_daily_prices_db.py..."
rm -f "tests/infrastructure/market_data/eod/test_unify_daily_prices_db.py"

# Remove duplicate of tests/domains/market_data/eod/test_unify_daily_prices.py
echo "Removing tests/infrastructure/market_data/eod/test_unify_daily_prices.py..."
rm -f "tests/infrastructure/market_data/eod/test_unify_daily_prices.py"

# Remove duplicate of tests/domains/market_data/eod/test_db_daily_price_market_data_manager.py
echo "Removing tests/infrastructure/market_data/eod/test_db_daily_price_market_data_manager.py..."
rm -f "tests/infrastructure/market_data/eod/test_db_daily_price_market_data_manager.py"

# Remove duplicate of tests/domains/market_data/eod/test_daily_adj.py
echo "Removing tests/infrastructure/market_data/eod/test_daily_adj.py..."
rm -f "tests/infrastructure/market_data/eod/test_daily_adj.py"

# Remove duplicate of tests/domains/market_data/news/test_comprehensive_news_backfill_integration.py
echo "Removing tests/infrastructure/market_data/news/test_comprehensive_news_backfill_integration.py..."
rm -f "tests/infrastructure/market_data/news/test_comprehensive_news_backfill_integration.py"

# Remove duplicate of tests/domains/market_data/news/test_turbo_news_backfill_integration.py
echo "Removing tests/infrastructure/market_data/news/test_turbo_news_backfill_integration.py..."
rm -f "tests/infrastructure/market_data/news/test_turbo_news_backfill_integration.py"

# Remove duplicate of tests/domains/market_data/agent/test_models.py
echo "Removing tests/infrastructure/market_data/agent/test_models.py..."
rm -f "tests/infrastructure/market_data/agent/test_models.py"

# Remove duplicate of tests/domains/market_data/agent/test_reconciliation.py
echo "Removing tests/infrastructure/market_data/agent/test_reconciliation.py..."
rm -f "tests/infrastructure/market_data/agent/test_reconciliation.py"

# Remove duplicate of tests/domains/market_data/agent/test_llm_assistant.py
echo "Removing tests/infrastructure/market_data/agent/test_llm_assistant.py..."
rm -f "tests/infrastructure/market_data/agent/test_llm_assistant.py"

# Remove duplicate of tests/domains/market_data/agent/test_reconciled_record_dao.py
echo "Removing tests/infrastructure/market_data/agent/test_reconciled_record_dao.py..."
rm -f "tests/infrastructure/market_data/agent/test_reconciled_record_dao.py"

# Remove duplicate of tests/domains/market_data/agent/test_orchestrator.py
echo "Removing tests/infrastructure/market_data/agent/test_orchestrator.py..."
rm -f "tests/infrastructure/market_data/agent/test_orchestrator.py"

# Remove duplicate of tests/domains/market_data/agent/test_data_agent_integration.py
echo "Removing tests/infrastructure/market_data/agent/test_data_agent_integration.py..."
rm -f "tests/infrastructure/market_data/agent/test_data_agent_integration.py"

# Remove duplicate of tests/domains/market_data/backfill/test_unified_backfill_orchestrator.py
echo "Removing tests/infrastructure/market_data/backfill/test_unified_backfill_orchestrator.py..."
rm -f "tests/infrastructure/market_data/backfill/test_unified_backfill_orchestrator.py"

# Remove duplicate of tests/domains/market_data/backfill/test_enhanced_minute_backfill_orchestrator.py
echo "Removing tests/infrastructure/market_data/backfill/test_enhanced_minute_backfill_orchestrator.py..."
rm -f "tests/infrastructure/market_data/backfill/test_enhanced_minute_backfill_orchestrator.py"

# Remove duplicate of tests/domains/market_data/reconciliation/test_majority_voting_reconciler.py
echo "Removing tests/infrastructure/market_data/reconciliation/test_majority_voting_reconciler.py..."
rm -f "tests/infrastructure/market_data/reconciliation/test_majority_voting_reconciler.py"

# Remove duplicate of tests/domains/market_data/reconciliation/test_cross_vendor_reconciler.py
echo "Removing tests/infrastructure/market_data/reconciliation/test_cross_vendor_reconciler.py..."
rm -f "tests/infrastructure/market_data/reconciliation/test_cross_vendor_reconciler.py"

# Remove duplicate of tests/domains/market_data/reconciliation/test_timezone_fix.py
echo "Removing tests/infrastructure/market_data/reconciliation/test_timezone_fix.py..."
rm -f "tests/infrastructure/market_data/reconciliation/test_timezone_fix.py"

# Remove duplicate of tests/domains/market_data/realtime/test_aapl_tsla_collectors.py
echo "Removing tests/infrastructure/market_data/realtime/test_aapl_tsla_collectors.py..."
rm -f "tests/infrastructure/market_data/realtime/test_aapl_tsla_collectors.py"

# Remove duplicate of tests/domains/market_data/realtime/test_gap_detector.py
echo "Removing tests/infrastructure/market_data/realtime/test_gap_detector.py..."
rm -f "tests/infrastructure/market_data/realtime/test_gap_detector.py"

# Remove duplicate of tests/domains/market_data/realtime/test_performance_benchmarks.py
echo "Removing tests/infrastructure/market_data/realtime/test_performance_benchmarks.py..."
rm -f "tests/infrastructure/market_data/realtime/test_performance_benchmarks.py"

# Remove duplicate of tests/domains/market_data/realtime/test_streaming_collector.py
echo "Removing tests/infrastructure/market_data/realtime/test_streaming_collector.py..."
rm -f "tests/infrastructure/market_data/realtime/test_streaming_collector.py"

# Remove duplicate of tests/domains/market_data/realtime/test_weekly_backfill.py
echo "Removing tests/infrastructure/market_data/realtime/test_weekly_backfill.py..."
rm -f "tests/infrastructure/market_data/realtime/test_weekly_backfill.py"

# Remove duplicate of tests/domains/market_data/realtime/test_daily_validation.py
echo "Removing tests/infrastructure/market_data/realtime/test_daily_validation.py..."
rm -f "tests/infrastructure/market_data/realtime/test_daily_validation.py"

# Remove duplicate of tests/domains/market_data/realtime/test_metrics_exporter.py
echo "Removing tests/infrastructure/market_data/realtime/test_metrics_exporter.py..."
rm -f "tests/infrastructure/market_data/realtime/test_metrics_exporter.py"

# Remove duplicate of tests/infrastructure/web/ui_tests/test_eda_playwright_simple.py
echo "Removing tests/infrastructure/web/ui/test_eda_playwright_simple.py..."
rm -f "tests/infrastructure/web/ui/test_eda_playwright_simple.py"

# Remove duplicate of tests/domains/trading/integration/test_comprehensive_timeframe_validation.py
echo "Removing tests/core/unit/test_comprehensive_timeframe_validation.py..."
rm -f "tests/core/unit/test_comprehensive_timeframe_validation.py"

# Remove duplicate of tests/domains/instruments/integration/test_unified_instruments_integrity.py
echo "Removing tests/domains/instruments/services/test_unified_instruments_integrity.py..."
rm -f "tests/domains/instruments/services/test_unified_instruments_integrity.py"

# Remove duplicate of tests/domains/instruments/repositories/test_exchange_dao_integration.py
echo "Removing tests/domains/instruments/unit/test_exchange_dao_integration.py..."
rm -f "tests/domains/instruments/unit/test_exchange_dao_integration.py"

# Remove duplicate of tests/domains/instruments/services/test_market_cap_population.py
echo "Removing tests/domains/instruments/services/secmaster/test_market_cap_population.py..."
rm -f "tests/domains/instruments/services/secmaster/test_market_cap_population.py"

# Remove duplicate of tests/domains/instruments/services/test_secmaster_apis.py
echo "Removing tests/domains/instruments/services/secmaster/test_secmaster_apis.py..."
rm -f "tests/domains/instruments/services/secmaster/test_secmaster_apis.py"

# Remove duplicate of tests/domains/instruments/services/test_db_connection_local.py
echo "Removing tests/domains/instruments/services/secmaster/test_db_connection_local.py..."
rm -f "tests/domains/instruments/services/secmaster/test_db_connection_local.py"

# Remove duplicate of tests/domains/instruments/services/test_populate_unified_instruments.py
echo "Removing tests/domains/instruments/services/secmaster/test_populate_unified_instruments.py..."
rm -f "tests/domains/instruments/services/secmaster/test_populate_unified_instruments.py"

# Remove duplicate of tests/domains/instruments/services/test_split_logic.py
echo "Removing tests/domains/instruments/services/secmaster/test_split_logic.py..."
rm -f "tests/domains/instruments/services/secmaster/test_split_logic.py"

# Remove duplicate of tests/domains/instruments/services/test_secmaster.py
echo "Removing tests/domains/instruments/services/secmaster/test_secmaster.py..."
rm -f "tests/domains/instruments/services/secmaster/test_secmaster.py"

# Remove duplicate of tests/domains/instruments/services/test_db_connection.py
echo "Removing tests/domains/instruments/services/secmaster/test_db_connection.py..."
rm -f "tests/domains/instruments/services/secmaster/test_db_connection.py"

# Remove duplicate of tests/domains/instruments/services/test_advance.py
echo "Removing tests/domains/instruments/services/secmaster/test_advance.py..."
rm -f "tests/domains/instruments/services/secmaster/test_advance.py"

# Remove duplicate of tests/domains/instruments/services/test_secmaster_realdb.py
echo "Removing tests/domains/instruments/services/secmaster/test_secmaster_realdb.py..."
rm -f "tests/domains/instruments/services/secmaster/test_secmaster_realdb.py"

# Remove duplicate of tests/domains/ml/modeling/test_pytorch_multi_instrument_train.py
echo "Removing tests/domains/ml/ml/modeling/test_pytorch_multi_instrument_train.py..."
rm -f "tests/domains/ml/ml/modeling/test_pytorch_multi_instrument_train.py"

# Remove duplicate of tests/domains/ml/modeling/test_interpretability_framework.py
echo "Removing tests/domains/ml/ml/modeling/test_interpretability_framework.py..."
rm -f "tests/domains/ml/ml/modeling/test_interpretability_framework.py"

# Remove duplicate of tests/domains/ml/modeling/test_event_features.py
echo "Removing tests/domains/ml/ml/modeling/test_event_features.py..."
rm -f "tests/domains/ml/ml/modeling/test_event_features.py"

# Remove duplicate of tests/domains/ml/modeling/test_training_data_generator.py
echo "Removing tests/domains/ml/ml/modeling/test_training_data_generator.py..."
rm -f "tests/domains/ml/ml/modeling/test_training_data_generator.py"

# Remove duplicate of tests/domains/ml/modeling/test_enhanced_feature_types.py
echo "Removing tests/domains/ml/ml/modeling/test_enhanced_feature_types.py..."
rm -f "tests/domains/ml/ml/modeling/test_enhanced_feature_types.py"

# Remove duplicate of tests/domains/ml/modeling/test_factor_models.py
echo "Removing tests/domains/ml/ml/modeling/test_factor_models.py..."
rm -f "tests/domains/ml/ml/modeling/test_factor_models.py"

# Remove duplicate of tests/domains/ml/modeling/test_portfolio_evaluator.py
echo "Removing tests/domains/ml/ml/modeling/test_portfolio_evaluator.py..."
rm -f "tests/domains/ml/ml/modeling/test_portfolio_evaluator.py"

# Remove duplicate of tests/domains/ml/modeling/test_cross_timeframe_aligner.py
echo "Removing tests/domains/ml/ml/modeling/test_cross_timeframe_aligner.py..."
rm -f "tests/domains/ml/ml/modeling/test_cross_timeframe_aligner.py"

# Remove duplicate of tests/domains/ml/modeling/test_unified_loss_comprehensive.py
echo "Removing tests/domains/ml/ml/modeling/test_unified_loss_comprehensive.py..."
rm -f "tests/domains/ml/ml/modeling/test_unified_loss_comprehensive.py"

# Remove duplicate of tests/domains/ml/modeling/test_multi_timeframe_analyzer.py
echo "Removing tests/domains/ml/ml/modeling/test_multi_timeframe_analyzer.py..."
rm -f "tests/domains/ml/ml/modeling/test_multi_timeframe_analyzer.py"

# Remove duplicate of tests/domains/ml/modeling/test_configurable_train_data_generator_comprehensive.py
echo "Removing tests/domains/ml/ml/modeling/test_configurable_train_data_generator_comprehensive.py..."
rm -f "tests/domains/ml/ml/modeling/test_configurable_train_data_generator_comprehensive.py"

# Remove duplicate of tests/domains/ml/modeling/test_llm_pattern_recognition.py
echo "Removing tests/domains/ml/ml/modeling/test_llm_pattern_recognition.py..."
rm -f "tests/domains/ml/ml/modeling/test_llm_pattern_recognition.py"

# Remove duplicate of tests/domains/ml/modeling/test_unified_loss_performance.py
echo "Removing tests/domains/ml/ml/modeling/test_unified_loss_performance.py..."
rm -f "tests/domains/ml/ml/modeling/test_unified_loss_performance.py"

# Remove duplicate of tests/domains/ml/services/test_support_resistance_generator.py
echo "Removing tests/domains/ml/ml/test_support_resistance_generator.py..."
rm -f "tests/domains/ml/ml/test_support_resistance_generator.py"

# Remove duplicate of tests/domains/ml/services/test_sr_backtester.py
echo "Removing tests/domains/ml/ml/test_sr_backtester.py..."
rm -f "tests/domains/ml/ml/test_sr_backtester.py"

# Remove duplicate of tests/domains/ml/services/test_complete_sr_pipeline.py
echo "Removing tests/domains/ml/ml/test_complete_sr_pipeline.py..."
rm -f "tests/domains/ml/ml/test_complete_sr_pipeline.py"

# Remove duplicate of tests/domains/ml/services/test_adaptive_sr_model.py
echo "Removing tests/domains/ml/ml/test_adaptive_sr_model.py..."
rm -f "tests/domains/ml/ml/test_adaptive_sr_model.py"

# Remove duplicate of tests/domains/ml/services/test_type_system_demonstration.py
echo "Removing tests/domains/ml/ml/test_type_system_demonstration.py..."
rm -f "tests/domains/ml/ml/test_type_system_demonstration.py"

# Remove duplicate of tests/domains/ml/services/test_support_resistance_model.py
echo "Removing tests/domains/ml/ml/test_support_resistance_model.py..."
rm -f "tests/domains/ml/ml/test_support_resistance_model.py"

# Remove duplicate of tests/domains/ml/models/test_data_loader.py
echo "Removing tests/domains/ml/ml/models/test_data_loader.py..."
rm -f "tests/domains/ml/ml/models/test_data_loader.py"

# Remove duplicate of tests/domains/ml/models/test_temporal_fusion_transformer.py
echo "Removing tests/domains/ml/ml/models/test_temporal_fusion_transformer.py..."
rm -f "tests/domains/ml/ml/models/test_temporal_fusion_transformer.py"

# Remove duplicate of tests/domains/ml/unit/test_timeseries_sequence_training_generator_aggregation.py
echo "Removing tests/domains/ml/services/training_data/test_timeseries_sequence_training_generator_aggregation.py..."
rm -f "tests/domains/ml/services/training_data/test_timeseries_sequence_training_generator_aggregation.py"

# Remove duplicate of tests/domains/ml/unit/test_training_data_uses_future_universe_state_intervals.py
echo "Removing tests/domains/ml/services/training_data/test_training_data_uses_future_universe_state_intervals.py..."
rm -f "tests/domains/ml/services/training_data/test_training_data_uses_future_universe_state_intervals.py"

# Remove duplicate of tests/domains/ml/unit/test_training_data_uses_universe_state_intervals.py
echo "Removing tests/domains/ml/services/training_data/test_training_data_uses_universe_state_intervals.py..."
rm -f "tests/domains/ml/services/training_data/test_training_data_uses_universe_state_intervals.py"

# Remove duplicate of tests/domains/ml/unit/test_training_data_temporal_isolation.py
echo "Removing tests/domains/ml/services/training_data/test_training_data_temporal_isolation.py..."
rm -f "tests/domains/ml/services/training_data/test_training_data_temporal_isolation.py"

# Remove duplicate of tests/domains/ml/unit/test_training_data_serialization.py
echo "Removing tests/domains/ml/services/training_data/test_training_data_serialization.py..."
rm -f "tests/domains/ml/services/training_data/test_training_data_serialization.py"

# Remove duplicate of tests/domains/ml/training_data/test_single_file_multi_day_arrayrecord.py
echo "Removing tests/domains/ml/services/training_data/test_single_file_multi_day_arrayrecord.py..."
rm -f "tests/domains/ml/services/training_data/test_single_file_multi_day_arrayrecord.py"

# Remove duplicate of tests/domains/ml/training_data/test_database_registration_failure.py
echo "Removing tests/domains/ml/services/training_data/test_database_registration_failure.py..."
rm -f "tests/domains/ml/services/training_data/test_database_registration_failure.py"

# Remove duplicate of tests/domains/ml/training_data/test_structure_issues.py
echo "Removing tests/domains/ml/services/training_data/test_structure_issues.py..."
rm -f "tests/domains/ml/services/training_data/test_structure_issues.py"

# Remove duplicate of tests/domains/ml/training_data/test_dynamic_technical_indicators.py
echo "Removing tests/domains/ml/services/training_data/test_dynamic_technical_indicators.py..."
rm -f "tests/domains/ml/services/training_data/test_dynamic_technical_indicators.py"

# Remove duplicate of tests/domains/ml/training/test_multimodal_dataset_generator.py
echo "Removing tests/domains/ml/services/training/test_multimodal_dataset_generator.py..."
rm -f "tests/domains/ml/services/training/test_multimodal_dataset_generator.py"

# Remove duplicate of tests/domains/ml/services/training_data/test_news_event_integration.py
echo "Removing tests/domains/ml/ml/training_data/test_news_event_integration.py..."
rm -f "tests/domains/ml/ml/training_data/test_news_event_integration.py"

# Remove duplicate of tests/domains/ml/services/training/hourly_data_generation/test_hourly_aggregation.py
echo "Removing tests/domains/ml/training/hourly_data_generation/test_hourly_aggregation.py..."
rm -f "tests/domains/ml/training/hourly_data_generation/test_hourly_aggregation.py"

# Remove duplicate of tests/domains/ml/services/training/hourly_data_generation/test_simple_aggregation.py
echo "Removing tests/domains/ml/training/hourly_data_generation/test_simple_aggregation.py..."
rm -f "tests/domains/ml/training/hourly_data_generation/test_simple_aggregation.py"

# Remove duplicate of tests/domains/ml/services/training/hourly_data_generation/test_integration.py
echo "Removing tests/domains/ml/training/hourly_data_generation/test_integration.py..."
rm -f "tests/domains/ml/training/hourly_data_generation/test_integration.py"

# Remove duplicate of tests/domains/ml/services/training/hourly_data_generation/test_universe_state_integration.py
echo "Removing tests/domains/ml/training/hourly_data_generation/test_universe_state_integration.py..."
rm -f "tests/domains/ml/training/hourly_data_generation/test_universe_state_integration.py"

# Remove duplicate of tests/domains/ml/services/training/hourly_data_generation/test_with_real_data.py
echo "Removing tests/domains/ml/training/hourly_data_generation/test_with_real_data.py..."
rm -f "tests/domains/ml/training/hourly_data_generation/test_with_real_data.py"

# Remove duplicate of tests/domains/ml/ml/models/attention/test_cross_scale_attention.py
echo "Removing tests/domains/ml/models/attention/test_cross_scale_attention.py..."
rm -f "tests/domains/ml/models/attention/test_cross_scale_attention.py"

echo ""
echo "✅ Duplicate removal complete!"
echo "Run: pytest --collect-only to verify no import mismatch errors"
