# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factor_interval.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66\x61\x63tor_interval.proto\x12\x05state\x1a\x19instrument_interval.proto\"\xff\x01\n\x0e\x46\x61\x63torInterval\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x0fstart_date_time\x18\x03 \x01(\t\x12\x15\n\rend_date_time\x18\x04 \x01(\t\x12L\n\x14instrument_intervals\x18\x05 \x03(\x0b\x32..state.FactorInterval.InstrumentIntervalsEntry\x1aU\n\x18InstrumentIntervalsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.state.InstrumentInterval:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factor_interval_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACTORINTERVAL_INSTRUMENTINTERVALSENTRY._options = None
  _FACTORINTERVAL_INSTRUMENTINTERVALSENTRY._serialized_options = b'8\001'
  _FACTORINTERVAL._serialized_start=60
  _FACTORINTERVAL._serialized_end=315
  _FACTORINTERVAL_INSTRUMENTINTERVALSENTRY._serialized_start=230
  _FACTORINTERVAL_INSTRUMENTINTERVALSENTRY._serialized_end=315
# @@protoc_insertion_point(module_scope)
