#!/usr/bin/env python3
"""
Trading Calendar Architecture Verification Test

Verifies the new event-driven architecture for 1d/1w timeframe generation:
- Runner emits trading_day_end and trading_week_end events based on exchange calendar
- Training callback responds to these events (not hardcoded times)
- UniverseStateBuilder responds to these events (not hardcoded times)
- Timing is based on actual market close, respects holidays/early close

This replaces the broken hardcoded time approach with proper trading calendar events.
"""

import pytest
import asyncio
import logging
from datetime import datetime, date, timedelta
from unittest.mock import Mock, AsyncMock, patch
from typing import List, Dict, Any

import sys
sys.path.insert(0, 'src')

from domains.trading.services.core.app.runner import Runner
from core.platform.config.environment import Environment, EnvironmentType
from domains.ml.services.training_data.callbacks.training_data_callback import IntervalBasedTrainingDataCallback
from domains.trading.services.state.universe_state_builder import UniverseStateIntervalBuilder


class TestTradingCalendarArchitecture:
    """Test the new trading calendar event architecture."""

    @pytest.fixture
    def test_environment(self):
        """Create test environment."""
        return Environment(
            env_type=EnvironmentType.TEST,
            db_url="postgresql://test_user:test_password@localhost:5432/test_db"
        )

    @pytest.fixture
    def mock_universe_manager(self):
        """Mock universe manager."""
        manager = Mock()
        manager.instrument_ids = [1, 2, 3]  # 3 test instruments
        return manager

    @pytest.fixture
    def mock_universe_state_manager(self):
        """Mock universe state manager."""
        manager = Mock()
        manager.addUniverseState = AsyncMock()
        manager.ensure_timeframe_cache = Mock()
        manager.get_instrument_history_for_timeframe = Mock(return_value=[])
        manager.add_interval_to_rolling_cache = Mock()
        return manager

    @pytest.fixture
    def mock_market_data_manager(self):
        """Mock market data manager."""
        manager = Mock()
        manager.exchange = 'NYSE'  # Use NYSE for testing
        manager.update_for_sod = AsyncMock()
        manager.update_for_eod = AsyncMock()
        return manager

    @pytest.fixture
    def mock_security_master(self):
        """Mock security master."""
        master = Mock()
        master.update_for_sod = AsyncMock()
        master.update_for_eod = AsyncMock()
        return master

    def test_runner_generates_trading_calendar_events(self, test_environment, mock_universe_manager, 
                                                    mock_universe_state_manager, mock_market_data_manager, 
                                                    mock_security_master):
        """Test that Runner generates trading_day_end and trading_week_end events."""
        print("🔍 Testing Runner trading calendar event generation")
        
        # Create runner for a single week (July 1-5, 2025 - should be Mon-Fri)
        runner = Runner(
            start_date="2025-07-01",  # Tuesday 
            end_date="2025-07-03",    # Thursday
            environment=test_environment,
            universe_id=1,
            callbacks=[],
            base_duration="5m",
            universe_manager=mock_universe_manager,
            universe_state_manager=mock_universe_state_manager,
            market_data_manager=mock_market_data_manager,
            security_master=mock_security_master,
            # NYSE trading hours: 9:30 AM - 4:00 PM ET
            trading_start_hour=9,
            trading_start_minute=30,
            trading_end_hour=16,
            trading_end_minute=0,
            timezone='America/New_York'
        )
        
        # Collect events generated by runner
        events = list(runner.iter_events())
        
        # Extract event types and times
        event_info = [(event_time, event_type) for event_time, event_type in events]
        
        print(f"📊 Generated {len(events)} events:")
        for event_time, event_type in event_info:
            print(f"   {event_type}: {event_time}")
        
        # Verify we have the expected event types
        event_types = [event_type for _, event_type in event_info]
        
        assert "start" in event_types, "Should have start event"
        assert "trading_day_end" in event_types, "Should have trading_day_end events"
        assert "interval" in event_types, "Should have interval events"
        assert "eod" in event_types, "Should have traditional eod events"
        assert "end" in event_types, "Should have end event"
        
        # Verify trading_day_end events occur at 4 PM (market close)
        trading_day_end_events = [(t, e) for t, e in event_info if e == "trading_day_end"]
        print(f"📊 Found {len(trading_day_end_events)} trading_day_end events")
        
        for event_time, _ in trading_day_end_events:
            assert event_time.hour == 16, f"Trading day end should be at 4 PM, got {event_time.hour}:00"
            assert event_time.minute == 0, f"Trading day end should be at :00, got :{event_time.minute}"
            print(f"   ✅ Trading day end at {event_time} (4:00 PM ET)")
        
        # For 3-day period (Tue-Thu), should have trading_week_end on Thursday if it's last day of week
        trading_week_end_events = [(t, e) for t, e in event_info if e == "trading_week_end"]
        print(f"📊 Found {len(trading_week_end_events)} trading_week_end events")
        
        if trading_week_end_events:
            for event_time, _ in trading_week_end_events:
                assert event_time.hour == 16, f"Trading week end should be at 4 PM, got {event_time.hour}:00"
                print(f"   ✅ Trading week end at {event_time} (4:00 PM ET)")
        
        print("✅ Runner correctly generates trading calendar events at market close times")

    @pytest.mark.asyncio
    async def test_training_callback_responds_to_trading_events(self, test_environment):
        """Test that training callback responds to trading_day_end and trading_week_end events."""
        print("🔍 Testing training callback response to trading calendar events")
        
        # Create training callback
        callback = IntervalBasedTrainingDataCallback(
            symbols=['AAPL'],
            start_date=datetime(2025, 7, 1),
            end_date=datetime(2025, 7, 3),
            output_dir='/tmp/test_training',
            storage_format='arrayrecord'
        )
        
        # Mock dependencies
        callback.training_generator = Mock()
        callback.training_generator.generate_training_example = AsyncMock(return_value={
            'symbol': 'AAPL',
            'timeframe_features': {
                '1d': {'open': 150.0, 'close': 155.0},
                '1w': {'open': 150.0, 'close': 160.0}
            }
        })
        callback._save_simple_arrayrecord = AsyncMock()
        
        mock_runner = Mock()
        test_time = datetime(2025, 7, 1, 16, 0, 0)  # 4 PM ET
        
        # Test handleTradingDayEnd
        print("📊 Testing handleTradingDayEnd...")
        await callback.handleTradingDayEnd(mock_runner, test_time)
        
        # Verify 1d training example was generated
        callback.training_generator.generate_training_example.assert_called_with(
            symbol='AAPL',
            prediction_timestamp=test_time,
            target_timeframes=['1d']
        )
        
        # Verify data was saved
        callback._save_simple_arrayrecord.assert_called()
        save_args = callback._save_simple_arrayrecord.call_args
        saved_examples = save_args[0][0]  # First positional argument
        assert len(saved_examples) == 1, "Should save 1 example for 1 symbol"
        assert saved_examples[0]['timeframe_features']['1d']['close'] == 155.0
        
        print("   ✅ handleTradingDayEnd generates 1d training data")
        
        # Reset mocks for weekly test
        callback.training_generator.generate_training_example.reset_mock()
        callback._save_simple_arrayrecord.reset_mock()
        
        # Test handleTradingWeekEnd 
        print("📊 Testing handleTradingWeekEnd...")
        await callback.handleTradingWeekEnd(mock_runner, test_time)
        
        # Verify 1w training example was generated
        callback.training_generator.generate_training_example.assert_called_with(
            symbol='AAPL',
            prediction_timestamp=test_time,
            target_timeframes=['1w']
        )
        
        # Verify data was saved
        callback._save_simple_arrayrecord.assert_called()
        save_args = callback._save_simple_arrayrecord.call_args
        saved_examples = save_args[0][0]
        assert len(saved_examples) == 1
        assert saved_examples[0]['timeframe_features']['1w']['close'] == 160.0
        
        print("   ✅ handleTradingWeekEnd generates 1w training data")
        print("✅ Training callback correctly responds to trading calendar events")

    @pytest.mark.asyncio  
    async def test_universe_state_builder_responds_to_trading_events(self, test_environment):
        """Test that UniverseStateBuilder responds to trading_day_end and trading_week_end events."""
        print("🔍 Testing UniverseStateBuilder response to trading calendar events")
        
        # Create UniverseStateBuilder
        from core.business.calendars.time_duration import TimeDuration
        
        builder = UniverseStateIntervalBuilder(
            env=test_environment,
            base_duration='5m',
            target_durations='5m,15m,60m,1d,1w'
        )
        
        # Mock dependencies  
        mock_runner = Mock()
        mock_runner.universe_id = 1
        mock_runner.universe_manager = Mock()
        mock_runner.universe_manager.instrument_ids = [1, 2, 3]
        mock_runner.universe_state_manager = Mock()
        mock_runner.universe_state_manager.addUniverseState = AsyncMock()
        
        # Mock the _build_universe_state_for_duration method
        builder._build_universe_state_for_duration = AsyncMock(return_value={
            TimeDuration('1d'): {'mock': 'universe_state_1d'},
            TimeDuration('1w'): {'mock': 'universe_state_1w'}
        })
        
        test_time = datetime(2025, 7, 1, 16, 0, 0)  # 4 PM ET
        
        # Test handleTradingDayEnd
        print("📊 Testing handleTradingDayEnd...")
        await builder.handleTradingDayEnd(mock_runner, test_time)
        
        # Verify universe state building was called for 1d
        builder._build_universe_state_for_duration.assert_called()
        build_args = builder._build_universe_state_for_duration.call_args[0]
        duration_used = build_args[0]
        assert duration_used.get_duration_string() == '1d', "Should build 1d universe state"
        
        # Verify universe state was saved
        mock_runner.universe_state_manager.addUniverseState.assert_called()
        
        print("   ✅ handleTradingDayEnd builds 1d universe state")
        
        # Reset mocks for weekly test
        builder._build_universe_state_for_duration.reset_mock()
        mock_runner.universe_state_manager.addUniverseState.reset_mock()
        
        # Test handleTradingWeekEnd
        print("📊 Testing handleTradingWeekEnd...")
        await builder.handleTradingWeekEnd(mock_runner, test_time)
        
        # Verify universe state building was called for 1w
        builder._build_universe_state_for_duration.assert_called()
        build_args = builder._build_universe_state_for_duration.call_args[0]
        duration_used = build_args[0]
        assert duration_used.get_duration_string() == '1w', "Should build 1w universe state"
        
        # Verify universe state was saved
        mock_runner.universe_state_manager.addUniverseState.assert_called()
        
        print("   ✅ handleTradingWeekEnd builds 1w universe state")
        print("✅ UniverseStateBuilder correctly responds to trading calendar events")

    def test_no_hardcoded_times_in_interval_timeframe_logic(self):
        """Test that interval-based timeframe logic no longer generates 1d/1w at hardcoded times."""
        print("🔍 Testing removal of hardcoded times from interval logic")
        
        # Create training callback
        callback = IntervalBasedTrainingDataCallback(
            symbols=['AAPL'],
            start_date=datetime(2025, 7, 1),
            end_date=datetime(2025, 7, 3),
            output_dir='/tmp/test_training'
        )
        
        # Test various times throughout the day
        test_times = [
            datetime(2025, 7, 1, 0, 0, 0),   # Midnight
            datetime(2025, 7, 1, 9, 30, 0),  # Market open
            datetime(2025, 7, 1, 13, 35, 0), # Afternoon (the original error time!)
            datetime(2025, 7, 1, 16, 0, 0),  # Market close
            datetime(2025, 7, 1, 23, 59, 0), # End of day
        ]
        
        for test_time in test_times:
            timeframes = callback._get_target_timeframes_for_interval(test_time)
            
            # 1d and 1w should NEVER be in interval-based timeframes now
            assert '1d' not in timeframes, f"1d should not be generated at {test_time} via intervals"
            assert '1w' not in timeframes, f"1w should not be generated at {test_time} via intervals"
            
            print(f"   ✅ {test_time}: No 1d/1w in interval timeframes: {timeframes}")
        
        print("✅ Hardcoded times removed - 1d/1w generation now purely event-driven")


if __name__ == "__main__":
    """
    Run verification test to confirm new trading calendar architecture works.
    
    Expected outcome: All tests pass, confirming event-driven architecture.
    """
    print("🔍 RUNNING TRADING CALENDAR ARCHITECTURE VERIFICATION")
    print("=" * 70)
    print("Expected: All tests pass, confirming new event-driven approach")
    print("Goal: Verify 1d/1w generation via trading calendar events, not hardcoded times")
    print("=" * 70)
    
    # Run with verbose output for verification
    pytest.main([__file__, "-v", "--tb=long", "-s"])