#!/usr/bin/env python3
"""
Test to reproduce ValueError in _save_monthly_training_data_records.

The issue occurs when file keys include feature groups but the parsing logic
doesn't account for the extra component in the filename structure.

Expected file key format (parsing assumes): symbol_timeframe_YYYY_MM  
Actual file key format (what's generated): symbol_featuregroup_timeframe_YYYY_MM

This causes int(parts[2]) to fail when parts[2] is 'basic' instead of a year.
"""

import pytest
import asyncio
from datetime import datetime, date
from unittest.mock import Mock, AsyncMock
from pathlib import Path

import sys
sys.path.insert(0, 'src')

from domains.ml.services.training_data.callbacks.training_data_callback import IntervalBasedTrainingDataCallback


class TestMonthlyTrainingDataParsingBug:
    """Test reproduction of the file key parsing ValueError bug."""

    def test_file_key_parsing_bug_reproduction(self):
        """
        Reproduce the exact ValueError when feature groups are included in file keys.
        
        This demonstrates the bug where:
        - File keys are generated as: AAPL_basic_5m_2025_07  
        - Parsing expects: AAPL_5m_2025_07
        - Results in int('basic') failing at line 567
        """
        print("🔍 Testing file key parsing bug reproduction")
        
        # Create callback with problematic file keys
        callback = IntervalBasedTrainingDataCallback(
            symbols=['AAPL'],
            start_date=datetime(2025, 7, 1),
            end_date=datetime(2025, 7, 31),
            output_dir='/tmp/test_training'
        )
        
        # Simulate the actual file keys generated by the system (with feature groups)
        callback.monthly_file_paths = {
            'AAPL_basic_5m_2025_07': '/tmp/test_training/dataset_123/AAPL/5m/2025_07_basic.arrayrecord',
            'AAPL_basic_15m_2025_07': '/tmp/test_training/dataset_123/AAPL/15m/2025_07_basic.arrayrecord',
            'TSLA_basic_5m_2025_07': '/tmp/test_training/dataset_123/TSLA/5m/2025_07_basic.arrayrecord'
        }
        
        # Mock the dependencies
        mock_runner = Mock()
        mock_runner.run_context = Mock()
        mock_runner.run_context.run_id = "run_20250922_134918_aeda6fc8"
        mock_runner.get_environment = Mock(return_value=Mock())
        
        # Mock the DAOs and tracker to avoid database calls
        with pytest.raises(ValueError, match="invalid literal for int.*'5m'"):
            # This should fail when trying to parse '5m' as an integer
            asyncio.run(callback._save_monthly_training_data_records(mock_runner))
        
        print("   ✅ Successfully reproduced ValueError: int('5m') parsing error")

    def test_expected_file_key_format_works(self):
        """
        Test that the expected file key format (without feature groups) works correctly.
        
        This shows what the parsing logic was designed to handle.
        """
        print("🔍 Testing expected file key format (without feature groups)")
        
        callback = IntervalBasedTrainingDataCallback(
            symbols=['AAPL'],
            start_date=datetime(2025, 7, 1),
            end_date=datetime(2025, 7, 31),
            output_dir='/tmp/test_training'
        )
        
        # Use the expected format (without feature groups)
        callback.monthly_file_paths = {
            'AAPL_5m_2025_07': '/tmp/test_training/dataset_123/AAPL/5m/2025_07.arrayrecord',
            'AAPL_15m_2025_07': '/tmp/test_training/dataset_123/AAPL/15m/2025_07.arrayrecord',
            'TSLA_5m_2025_07': '/tmp/test_training/dataset_123/TSLA/5m/2025_07.arrayrecord'
        }
        
        # Test parsing logic manually
        for file_key in callback.monthly_file_paths.keys():
            parts = file_key.split('_')
            print(f"   File key: {file_key}")
            print(f"   Parts: {parts}")
            
            if len(parts) >= 4:
                symbol = parts[0]
                timeframe = parts[1]
                year = int(parts[2])  # This should work
                month = int(parts[3])  # This should work
                
                print(f"   ✅ Parsed: {symbol}, {timeframe}, {year}, {month}")
            else:
                print(f"   ❌ Insufficient parts: {len(parts)}")
        
        print("   ✅ Expected format parses correctly")

    def test_root_cause_analysis(self):
        """
        Analyze the root cause: mismatch between file key generation and parsing.
        
        Shows the exact discrepancy in the format expectations.
        """
        print("🔍 Root cause analysis: file key format mismatch")
        
        # What the generation code creates (with feature groups)
        generated_keys = [
            "AAPL_basic_5m_2025_07",    # symbol_featuregroup_timeframe_YYYY_MM
            "AAPL_basic_15m_2025_07", 
            "TSLA_advanced_5m_2025_07"
        ]
        
        # What the parsing code expects
        expected_format = [
            "AAPL_5m_2025_07",          # symbol_timeframe_YYYY_MM  
            "AAPL_15m_2025_07",
            "TSLA_5m_2025_07"
        ]
        
        print("📊 Format comparison:")
        print("   Generated (actual):  symbol_featuregroup_timeframe_YYYY_MM")
        print("   Expected (parsing):  symbol_timeframe_YYYY_MM")
        print()
        
        for i, (generated, expected) in enumerate(zip(generated_keys, expected_format)):
            print(f"   Example {i+1}:")
            print(f"     Generated: {generated}")
            print(f"     Expected:  {expected}")
            
            # Show what happens during parsing
            parts = generated.split('_')
            print(f"     Parts: {parts}")
            print(f"     parts[0] (symbol): {parts[0]}")
            print(f"     parts[1] (expected timeframe): {parts[1]} <- WRONG: This is feature group!")
            print(f"     parts[2] (expected year): {parts[2]} <- WRONG: This is timeframe!")
            print(f"     parts[3] (expected month): {parts[3]} <- WRONG: This is year!")
            print()
        
        print("   🚨 ISSUE: Feature group insertion shifts all parsing positions")
        print("   💡 SOLUTION: Update parsing logic to handle feature groups OR adjust generation")


if __name__ == "__main__":
    """
    Run test to reproduce and analyze the file key parsing bug.
    
    Expected outcome: Demonstrates the ValueError and root cause.
    """
    print("🔍 RUNNING MONTHLY TRAINING DATA PARSING BUG REPRODUCTION")
    print("=" * 70)
    print("Expected: ValueError when parsing file keys with feature groups")
    print("Goal: Understand mismatch between generation and parsing formats")
    print("=" * 70)
    
    # Run with verbose output for analysis
    pytest.main([__file__, "-v", "--tb=long", "-s"])