# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: instrument_interval.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19instrument_interval.proto\x12\x05state\"\xe5\x01\n\x12InstrumentInterval\x12\x15\n\rinstrument_id\x18\x01 \x01(\x05\x12\x17\n\x0fstart_date_time\x18\x02 \x01(\t\x12\x15\n\rend_date_time\x18\x03 \x01(\t\x12\x0c\n\x04open\x18\x04 \x01(\x01\x12\x0c\n\x04high\x18\x05 \x01(\x01\x12\x0b\n\x03low\x18\x06 \x01(\x01\x12\r\n\x05\x63lose\x18\x07 \x01(\x01\x12\x15\n\rtraded_volume\x18\x08 \x01(\x01\x12\x15\n\rtraded_dollar\x18\t \x01(\x01\x12\x0e\n\x06status\x18\n \x01(\t\x12\x12\n\nmarket_cap\x18\x0b \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instrument_interval_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTRUMENTINTERVAL._serialized_start=37
  _INSTRUMENTINTERVAL._serialized_end=266
# @@protoc_insertion_point(module_scope)
